config/routes.rb
Projeto::Application.routes.draw do
  resources :posts do
    resources :comentarios
  end
  
  resources :teste  
  match 'logout' => 'session#logout'
  match 'login' => 'session#login'
  match 'authenticate' => 'session#authenticate'
  

end

app/models/comentario.rb
class Comentario
  include MongoMapper::Document

  key :autor, String
  key :texto, String

  belongs_to :post
end

app/models/post.rb
class Post
  include MongoMapper::Document

  key :titulo, String, :required => true
  key :conteudo, String
  
  many :comentarios
  
  timestamps!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  def new
    @comentario = Comentario.new
    @post = Post.find(params[:post_id])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentario }
    end
  end

  def edit
    @comentario = Comentario.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def create
    @comentario = Comentario.create!(params[:comentario].merge({:post_id => params[:post_id]}))
    @post = Post.find(params[:post_id])
    
    redirect_to post_url(@post)
  end

  def update
     @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render json: @comentario, status: :created, location: @comentario }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
#encoding: utf-8
class PostsController < ApplicationController
  before_filter :authentication, :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(:created_at).page(params[:page]).per(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.comentarios = Comentario.all(:post_id => params[:id]) || []  

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

private

  def authentication
    if session[:username].nil?
      redirect_to login_path, :alert => "Você precisa estar logado para ter acesso"
    end
  end
end

app/controllers/teste_controller.rb
class TesteController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def show_links_for(post)
    html = [link_to('Show', post)]

    if session[:username]
      html << " "+link_to('Edit', edit_post_path(post))
      html << " "+link_to('Destroy', post, method: :delete, data: { confirm: 'Are you sure?' })
    end

    html.join(" ").html_safe
  end
end

app/views/comentarios/edit.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :texto %><br />
    <%= f.text_field :texto %>
  </div>
  <div class="field">
    <input type="hidden" value="<%= @post_id %>">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/new.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :texto %><br />
    <%= f.text_field :texto %>
  </div>
  <div class="field">
    <input type="hidden" value="<%= @post.id %>">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projeto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_field :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>


<%= I18n.l Time.now %>

<table>
  <tr>
    <th><%= t 'post.title'%></th>
    <th>Conteudo</th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.titulo %></td>
    <td><%= post.conteudo %></td>
    <td>
      <%= show_links_for(post) %>
    </td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @posts%>

<% if session[:username] %>
  <%= link_to 'Logout', logout_path %>
<% else %>
  <%= link_to 'Login', login_path %>
<% end %>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @post.titulo %>
</p>

<p>
  <b>Conteudo:</b>
  <%= simple_format(@post.conteudo) %>
</p>

<p>
  <b>Comentários:</b>
    <% @post.comentarios.each do |c| %>
      <p><%= c.autor %></p>
      <%= simple_format(c.texto) %>
    <% end %>
</p>

<h2>Adicionar comentário</h2>

<%= form_for([@post, @post.comentarios.build]) do |f| %>
  <%= f.label :autor %>
  <%= f.text_field :autor %><br />
  <%= f.label :texto %>
	<%= f.text_field :texto %><br />
  <%= f.submit%>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/teste/index.html.erb
<%= form_tag do %>
  
  
  <%= end %>

app/views/teste/show.html.erb
<%= form_tag do %>
<%= text_field_tag :person%><br/> 
<%= text_area_tag :person%> <br/>
<%= password_field_tag :person%> <br/>
<%= text_field_tag :person%> <br/>
<%= text_field_tag :person%> <br/>
<%= text_field_tag :person%> <br/>
 
  
<% end %>